sudo: required
services:
  - docker

before_install:
  - docker build -t madhu/react -f Dockerfile.dev .

script:
  - docker run -e CI=true madhu/react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react"
  env: "React-env"
  bucket_name: "elasticbeanstalk-ap-south-1-287611333539"
  bucket_path: "react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
